import React, { useState, useEffect } from 'react';
import { 
  Calendar, CheckCircle2, Clock, Phone, AlertCircle, 
  School, Check, ArrowRight, RefreshCw, Sparkles, IndianRupee 
} from 'lucide-react';
import { fetchFollowups, completeFollowup, fetchDemos } from '../../utils/callingApi';

export default function FollowupsAndDemos() {
  const [activeTab, setActiveTab] = useState('followups'); // 'followups' | 'demos'
  const [followups, setFollowups] = useState([]);
  const [demos, setDemos] = useState([]);
  const [loading, setLoading] = useState(true);

  const loadData = async () => {
    try {
      setLoading(true);
      const [fRes, dRes] = await Promise.all([
        fetchFollowups().catch(() => ({ followups: [] })),
        fetchDemos().catch(() => ({ demos: [] }))
      ]);
      setFollowups(fRes.followups || []);
      setDemos(dRes.demos || []);
    } catch (err) {
      console.error('Failed to load followups/demos:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleComplete = async (id) => {
    try {
      await completeFollowup(id);
      loadData();
    } catch (err) {
      alert(`Failed to complete followup: ${err.message}`);
    }
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner */}
      <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-black uppercase tracking-wider bg-teal-50 text-teal-700 dark:bg-teal-500/20 dark:text-teal-300 border border-teal-200 dark:border-teal-500/30 flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5 text-teal-600 dark:text-teal-400" />
              Action Center
            </span>
            <span className="px-2 py-0.5 rounded-full text-[11px] font-semibold bg-indigo-50 text-indigo-700 dark:bg-indigo-500/20 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-500/30">
              Sales Handoff Tracker
            </span>
          </div>
          <h1 className="text-xl md:text-2xl font-black text-slate-900 dark:text-white tracking-tight">
            Follow-up Tasks & Booked Demos
          </h1>
          <p className="text-xs md:text-sm text-slate-500 dark:text-slate-400 mt-1 max-w-2xl">
            Tasks generated by Ananya's qualification calls. Human sales reps pick up hot leads here to close annual partnerships.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {/* Sub Tab Switcher */}
          <div className="bg-slate-100 dark:bg-slate-950/80 p-1 rounded-xl border border-slate-200 dark:border-slate-800 flex items-center gap-1">
            <button
              onClick={() => setActiveTab('followups')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'followups'
                  ? 'bg-white dark:bg-indigo-600 text-slate-900 dark:text-white shadow-sm'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <Clock className="w-3.5 h-3.5" />
              Follow-ups ({followups.filter(f => !f.completed).length})
            </button>
            <button
              onClick={() => setActiveTab('demos')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'demos'
                  ? 'bg-white dark:bg-indigo-600 text-slate-900 dark:text-white shadow-sm'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <Calendar className="w-3.5 h-3.5" />
              Demos ({demos.length})
            </button>
          </div>

          <button
            onClick={loadData}
            className="p-2 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 rounded-xl transition cursor-pointer"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Content */}
      {loading ? (
        <div className="py-20 text-center text-slate-400 text-xs">
          Loading tasks and demos...
        </div>
      ) : activeTab === 'followups' ? (
        /* Followups List */
        followups.length === 0 ? (
          <div className="p-12 text-center rounded-2xl bg-slate-50 dark:bg-slate-900/60 border border-dashed border-slate-200 dark:border-slate-800">
            <p className="text-xs text-slate-500 dark:text-slate-400">All follow-ups completed! No pending tasks.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {followups.map((f) => {
              const isDone = f.completed;
              return (
                <div
                  key={f.id}
                  className={`p-4 rounded-xl border transition flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                    isDone 
                      ? 'bg-slate-50 dark:bg-slate-900/40 border-slate-200 dark:border-slate-800/60 opacity-60' 
                      : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700 shadow-sm'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <div className={`p-2 rounded-xl mt-0.5 ${
                      isDone ? 'bg-slate-200 dark:bg-slate-800 text-slate-500' : 'bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-400 border border-amber-200 dark:border-amber-500/20'
                    }`}>
                      <Clock className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-bold text-slate-900 dark:text-white">{f.school_name || 'Telangana School'}</span>
                        <span className="text-[10px] text-slate-500 dark:text-slate-400">• {f.district}</span>
                        <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-amber-50 text-amber-700 dark:bg-amber-500/20 dark:text-amber-400 border border-amber-200 dark:border-amber-500/30">
                          {f.action || 'CALL_BACK'}
                        </span>
                      </div>
                      <p className="text-xs text-slate-700 dark:text-slate-300 mt-1">{f.notes}</p>
                      <div className="text-[10px] text-slate-500 dark:text-slate-400 mt-1">
                        Phone: <span className="font-mono text-slate-700 dark:text-slate-300">{f.phone}</span> • Created: {f.created_at ? new Date(f.created_at).toLocaleDateString() : 'Today'}
                      </div>
                    </div>
                  </div>

                  <div className="self-end sm:self-center">
                    {!isDone ? (
                      <button
                        onClick={() => handleComplete(f.id)}
                        className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-lg shadow-sm transition flex items-center gap-1.5 cursor-pointer"
                      >
                        <Check className="w-3.5 h-3.5" />
                        Mark Done
                      </button>
                    ) : (
                      <span className="text-xs text-slate-500 font-semibold flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Completed
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )
      ) : (
        /* Demos List */
        demos.length === 0 ? (
          <div className="p-12 text-center rounded-2xl bg-slate-50 dark:bg-slate-900/60 border border-dashed border-slate-200 dark:border-slate-800">
            <p className="text-xs text-slate-500 dark:text-slate-400">No demos requested yet. Make AI calls to qualify schools and book demos.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {demos.map((d) => {
              const students = d.student_count || 450;
              const dealValue = students * 500;

              return (
                <div
                  key={d.id}
                  className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-purple-50 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300 border border-purple-200 dark:border-purple-500/30">
                        {d.scheduled_status || 'Requested'}
                      </span>
                      <span className="text-[10px] text-slate-500 dark:text-slate-400">
                        {d.created_at ? new Date(d.created_at).toLocaleDateString() : 'Today'}
                      </span>
                    </div>

                    <h3 className="text-sm font-bold text-slate-900 dark:text-white tracking-tight mb-1">
                      {d.school_name || 'Telangana High School'}
                    </h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mb-3">{d.district}</p>

                    <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 space-y-1.5 text-xs">
                      <div className="flex justify-between">
                        <span className="text-slate-500 dark:text-slate-400">Student Strength:</span>
                        <span className="font-bold text-slate-800 dark:text-slate-200">{students} Students</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-500 dark:text-slate-400">Target Annual Deal:</span>
                        <span className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center">
                          <IndianRupee className="w-3 h-3" /> {dealValue.toLocaleString('en-IN')}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="pt-4 mt-3 border-t border-slate-100 dark:border-slate-800/80">
                    <button
                      onClick={() => alert(`Demo details for ${d.school_name} sent to calendar`)}
                      className="w-full py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold rounded-lg shadow-sm transition flex items-center justify-center gap-1.5 cursor-pointer"
                    >
                      <Calendar className="w-3.5 h-3.5" />
                      Add to Google Calendar
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )
      )}

    </div>
  );
}
